"""
STEP 3: Generate C Header File
================================
Converts wake_model.tflite into a C header file (wake_model.h)
that can be compiled directly into Arduino firmware.

Why do we need this?
    The ESP32-S3 has no file system — it can't open files from disk.
    So we embed the model as a raw byte array in the firmware itself.
    The chip reads it from flash memory at boot time.

This script works on Windows, Mac, and Linux.
(On Mac/Linux you can also use: xxd -i wake_model.tflite > wake_model.h)

Requirements:
    No extra packages needed — uses only Python standard library.

Run:
    python 3_make_header.py

Input:  wake_model.tflite  (from step 2)
Output: wake_model.h       (copy this into your Arduino sketch folder)
"""

import os

print("=" * 50)
print("TinyML Wake Word Detector — Step 3: Header")
print("=" * 50)

INPUT_FILE  = "wake_model.tflite"
OUTPUT_FILE = "wake_model.h"

# Check input file exists
if not os.path.exists(INPUT_FILE):
    print(f"\n❌ Error: {INPUT_FILE} not found.")
    print("   Please run 2_convert_model.py first.")
    exit(1)

print(f"\nReading {INPUT_FILE}...")
with open(INPUT_FILE, "rb") as f:
    data = f.read()

print(f"Model size: {len(data)} bytes")
print(f"Generating {OUTPUT_FILE}...")

# -------------------------------------------------------
# FORMAT AS C BYTE ARRAY
# The xxd tool does this on Linux/Mac. We replicate it here
# in pure Python so Windows users don't need extra tools.
# -------------------------------------------------------
with open(OUTPUT_FILE, "w") as f:
    # Header guard — prevents the file being included twice
    f.write("#ifndef WAKE_MODEL_H\n")
    f.write("#define WAKE_MODEL_H\n\n")
    f.write("// Auto-generated by 3_make_header.py\n")
    f.write("// Do not edit manually — regenerate from wake_model.tflite\n\n")

    # The byte array — this IS the model, baked into firmware
    f.write("alignas(8) const unsigned char wake_model_tflite[] = {\n")

    # Write bytes in rows of 12 for readability
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        # Add comma after every row except the last
        comma = "," if i + 12 < len(data) else ""
        f.write(f"  {hex_values}{comma}\n")

    f.write("};\n\n")

    # Store the length so firmware knows how many bytes to read
    f.write(f"const unsigned int wake_model_tflite_len = {len(data)};\n\n")
    f.write("#endif  // WAKE_MODEL_H\n")

print(f"\n✅ {OUTPUT_FILE} generated successfully")
print(f"   Contains {len(data)} bytes embedded as a C array")
print(f"\n📋 Next steps:")
print(f"   1. Copy wake_model.h into your Arduino sketch folder")
print(f"   2. Open arduino/tinyml_wake_word/tinyml_wake_word.ino")
print(f"   3. Flash to your ESP32-S3")
